name: controle_financeiro
description: Aplicativo Flutter para controle financeiro pessoal

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.5.3
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.12.0
  flutter_secure_storage: ^9.2.4
  dio: ^5.9.0
  fl_chart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
